### ISSUE TITLE
Web site is not working

### ISSUE THREAD

**Issue by oboroc** [Wierzbowsky/Caslink#1]
readme.txt refers to http://www.podrezov.com/

That site is not working as of Feb 25, 2020

**Comment by Wierzbowsky** [comment]
Unfortunately the site is down since a few weeks and I don't have any estimate on when it will be back. The readme file can be found in the repository:

https://github.com/Wierzbowsky/Caslink/blob/master/readme.txt

**Comment by Wierzbowsky** [comment]
The site is back.
